apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dv6rethuu-go
  janus-idp.io/tekton: dv6rethuu-go
  backstage.io/kubernetes-id: dv6rethuu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dv6rethuu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
